#!/usr/bin/env node
'use strict';
const http=require('http'),crypto=require('crypto'),fs=require('fs'),path=require('path'),url=require('url');
const PORT=process.env.PORT||3000;
const JWT_SECRET=process.env.JWT_SECRET||'taqoptionke-secret-2026';
const ADMIN_KEY=process.env.ADMIN_KEY||'admin123';
const ADMIN_EMAIL=(process.env.ADMIN_EMAIL||'').toLowerCase().trim();
const MY_MPESA_NUMBER=process.env.MY_MPESA_NUMBER||'';
const USD_KES=Number(process.env.USD_KES_RATE||130);
const DATA_DIR=process.env.DATA_DIR||path.join(__dirname,'data');
const DB_FILE=path.join(DATA_DIR,'db.json');
const DATABASE_URL=process.env.DATABASE_URL||'';
const USDT_ADDRESS=process.env.USDT_ADDRESS||'TScp5kZKdMTUyEF8JgwzS7x1Ets9xiUPxi';
const ZETUPAY_SECRET_KEY=process.env.ZETUPAY_SECRET_KEY||'';
const ZETUPAY_BASE=process.env.ZETUPAY_BASE||'https://pay.zetupay.co.ke/api/v1';
const ZETUPAY_PAYOUT_URL=process.env.ZETUPAY_PAYOUT_URL||'https://pay.zetupay.co.ke/api/v1/payout/b2c';
const BREVO_API_KEY=process.env.BREVO_API_KEY||'';
const EMAIL_FROM_EMAIL=process.env.EMAIL_FROM_EMAIL||'';
const EMAIL_FROM_NAME=process.env.EMAIL_FROM_NAME||'TaqOptionKe';
const INDICES={vol10:{id:'vol10',name:'Vol 10 (1s)',base:9534.43,vol:2.5,decimals:2},vol25:{id:'vol25',name:'Vol 25 (1s)',base:6355.20,vol:5,decimals:2},vol50:{id:'vol50',name:'Vol 50 (1s)',base:3428.90,vol:10,decimals:2},vol75:{id:'vol75',name:'Vol 75 (1s)',base:1854.30,vol:15,decimals:2},vol100:{id:'vol100',name:'Vol 100 (1s)',base:970.50,vol:20,decimals:2}};

let pg=null;
if(DATABASE_URL){try{const{Pool}=require('pg');pg=new Pool({connectionString:DATABASE_URL,ssl:DATABASE_URL.includes('localhost')?false:{rejectUnauthorized:false}});}catch(e){console.error('[pg] module missing - run npm i pg');pg=null;}}
async function initPg(){if(!pg)return;try{
await pg.query(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT,email TEXT UNIQUE,phone TEXT,country_code TEXT,password TEXT,balance NUMERIC DEFAULT 0,demo_balance NUMERIC DEFAULT 10000,created_at BIGINT)`);
await pg.query(`CREATE TABLE IF NOT EXISTS trades(id TEXT PRIMARY KEY,user_id TEXT,account TEXT,idx TEXT,kind TEXT,prediction INT,stake NUMERIC,entry_digit INT,entry_price NUMERIC,opened_at BIGINT,expires_at BIGINT,status TEXT,profit NUMERIC,odds NUMERIC,exit_digit INT,exit_price NUMERIC,settled_at BIGINT)`);
await pg.query(`CREATE TABLE IF NOT EXISTS txs(id TEXT PRIMARY KEY,user_id TEXT,account TEXT,type TEXT,method TEXT,amount NUMERIC,kes_amount NUMERIC,phone TEXT,destination TEXT,reference TEXT,status TEXT,payment_key TEXT,checkout_url TEXT,receipt_number TEXT,paid_at BIGINT,claimed_at BIGINT,reason TEXT,zetupay JSONB,created_at BIGINT)`);
const u=await pg.query('SELECT * FROM users');
if(u.rows.length)db.users=u.rows.map(r=>({id:r.id,name:r.name,email:r.email,phone:r.phone||'',countryCode:r.country_code||'',password:r.password,balance:Number(r.balance)||0,demoBalance:r.demo_balance!=null?Number(r.demo_balance):10000,createdAt:Number(r.created_at)||Date.now()}));
const t=await pg.query('SELECT * FROM trades');
if(t.rows.length)db.trades=t.rows.map(r=>({id:r.id,userId:r.user_id,account:r.account,index:r.idx,kind:r.kind,prediction:r.prediction,stake:Number(r.stake),entryDigit:r.entry_digit,entryPrice:Number(r.entry_price),openedAt:Number(r.opened_at),expiresAt:Number(r.expires_at),status:r.status,profit:Number(r.profit)||0,odds:Number(r.odds),exitDigit:r.exit_digit,exitPrice:r.exit_price!=null?Number(r.exit_price):null,settledAt:r.settled_at?Number(r.settled_at):null}));
const x=await pg.query('SELECT * FROM txs');
if(x.rows.length)db.txs=x.rows.map(r=>({id:r.id,userId:r.user_id,account:r.account,type:r.type,method:r.method,amount:Number(r.amount)||0,kesAmount:r.kes_amount!=null?Number(r.kes_amount):null,phone:r.phone,destination:r.destination,reference:r.reference,status:r.status,paymentKey:r.payment_key,checkoutUrl:r.checkout_url,receiptNumber:r.receipt_number,paidAt:r.paid_at?Number(r.paid_at):null,claimedAt:r.claimed_at?Number(r.claimed_at):null,reason:r.reason,zetupay:r.zetupay,createdAt:Number(r.created_at)}));
console.log('[pg] loaded',db.users.length,'users,',db.trades.length,'trades,',db.txs.length,'txs');
}catch(e){console.error('[pg] init error:',e.message);}}
function pgUser(u){if(!pg)return;pg.query(`INSERT INTO users(id,name,email,phone,country_code,password,balance,demo_balance,created_at)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)ON CONFLICT(id)DO UPDATE SET name=EXCLUDED.name,email=EXCLUDED.email,phone=EXCLUDED.phone,country_code=EXCLUDED.country_code,password=EXCLUDED.password,balance=EXCLUDED.balance,demo_balance=EXCLUDED.demo_balance`,[u.id,u.name,u.email,u.phone||'',u.countryCode||'',u.password,u.balance||0,u.demoBalance!=null?u.demoBalance:10000,u.createdAt||Date.now()]).catch(e=>console.error('[pg] user:',e.message));}
function pgTrade(t){if(!pg)return;pg.query(`INSERT INTO trades(id,user_id,account,idx,kind,prediction,stake,entry_digit,entry_price,opened_at,expires_at,status,profit,odds,exit_digit,exit_price,settled_at)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)ON CONFLICT(id)DO UPDATE SET status=EXCLUDED.status,profit=EXCLUDED.profit,exit_digit=EXCLUDED.exit_digit,exit_price=EXCLUDED.exit_price,settled_at=EXCLUDED.settled_at`,[t.id,t.userId,t.account,t.index,t.kind,t.prediction,t.stake,t.entryDigit,t.entryPrice,t.openedAt,t.expiresAt,t.status,t.profit||0,t.odds,t.exitDigit!=null?t.exitDigit:null,t.exitPrice!=null?t.exitPrice:null,t.settledAt||null]).catch(e=>console.error('[pg] trade:',e.message));}
function pgTx(x){if(!pg)return;pg.query(`INSERT INTO txs(id,user_id,account,type,method,amount,kes_amount,phone,destination,reference,status,payment_key,checkout_url,receipt_number,paid_at,claimed_at,reason,zetupay,created_at)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19)ON CONFLICT(id)DO UPDATE SET status=EXCLUDED.status,payment_key=EXCLUDED.payment_key,checkout_url=EXCLUDED.checkout_url,receipt_number=EXCLUDED.receipt_number,paid_at=EXCLUDED.paid_at,claimed_at=EXCLUDED.claimed_at,reason=EXCLUDED.reason,zetupay=EXCLUDED.zetupay`,[x.id,x.userId,x.account||null,x.type,x.method||null,x.amount||0,x.kesAmount||null,x.phone||null,x.destination||null,x.reference||null,x.status||null,x.paymentKey||null,x.checkoutUrl||null,x.receiptNumber||null,x.paidAt||null,x.claimedAt||null,x.reason||null,x.zetupay?JSON.stringify(x.zetupay):null,x.createdAt||Date.now()]).catch(e=>console.error('[pg] tx:',e.message));}

let db={users:[],trades:[],txs:[],ticks:{}};
for(const id in INDICES)db.ticks[id]=[];
try{fs.mkdirSync(DATA_DIR,{recursive:true});if(fs.existsSync(DB_FILE)){const l=JSON.parse(fs.readFileSync(DB_FILE,'utf8'));Object.assign(db,l);for(const id in INDICES)if(!db.ticks[id])db.ticks[id]=[];}}catch(e){}
function save(){try{fs.writeFileSync(DB_FILE,JSON.stringify(db));}catch(e){}}
const findUser=e=>db.users.find(u=>u.email===e);
const findUserById=id=>db.users.find(u=>u.id===id);
function hashPw(pw){const s=crypto.randomBytes(16).toString('hex');return s+':'+crypto.scryptSync(pw,s,64).toString('hex');}
function checkPw(pw,stored){if(!stored||!stored.includes(':'))return false;const[s,h]=stored.split(':');try{const t=crypto.scryptSync(pw,s,64).toString('hex');return crypto.timingSafeEqual(Buffer.from(h,'hex'),Buffer.from(t,'hex'));}catch{return false;}}
function sign(p){const d=Buffer.from(JSON.stringify({...p,exp:Date.now()+2592000000})).toString('base64url');return d+'.'+crypto.createHmac('sha256',JWT_SECRET).update(d).digest('base64url');}
function verify(t){if(!t||typeof t!=='string')return null;const[d,s]=t.split('.');if(!d||!s)return null;const exp=crypto.createHmac('sha256',JWT_SECRET).update(d).digest('base64url');if(s!==exp)return null;try{const p=JSON.parse(Buffer.from(d,'base64url').toString());return p.exp<Date.now()?null:p;}catch{return null;}}
function lastDigit(p,dec){return Math.floor(Math.abs(p)*Math.pow(10,dec))%10;}
function calcOdds(kind,pred){if(kind==='even'||kind==='odd')return 1.952;if(kind==='matches')return 9.0;if(kind==='differs')return 1.05;if(kind==='over'){const w=9-pred;if(w<=0)return 500;return +(1+(10/w-1)*0.92).toFixed(3);}if(kind==='under'){const w=pred;if(w<=0)return 500;return +(1+(10/w-1)*0.92).toFixed(3);}return 1.95;}
const resetCodes={};
async function sendEmail(to,subject,html){if(!BREVO_API_KEY||!EMAIL_FROM_EMAIL){console.log('=== EMAIL (no Brevo) ===');console.log('To:',to);console.log('Code:',(html.match(/>(\d{6})</)||[])[1]||'?');console.log('=====================');return false;}try{var r=await fetch('https://api.brevo.com/v3/smtp/email',{method:'POST',headers:{'api-key':BREVO_API_KEY,'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({sender:{name:EMAIL_FROM_NAME,email:EMAIL_FROM_EMAIL},to:[{email:to}],subject:subject,htmlContent:html})});if(!r.ok){console.error('Brevo error:',await r.text());return false;}return true;}catch(e){console.error('Email error:',e.message);return false;}}
const state={};
for(const id in INDICES){const cfg=INDICES[id];state[id]={price:cfg.base};if(db.ticks[id].length<50){db.ticks[id]=[];let p=cfg.base;const now=Date.now();for(let i=0;i<150;i++){p=Math.max(1,p+(Math.random()-0.5)*cfg.vol);db.ticks[id].push({price:+p.toFixed(cfg.decimals),digit:lastDigit(p,cfg.decimals),time:now-(150-i)*1000});}state[id].price=p;save();}else{state[id].price=db.ticks[id][db.ticks[id].length-1].price;}}
const sseClients=new Set();
function broadcast(event,data){const payload='event: '+event+'\ndata: '+JSON.stringify(data)+'\n\n';for(const res of sseClients){try{res.write(payload);}catch{sseClients.delete(res);}}}
setInterval(()=>{const now=Date.now();for(const id in INDICES){const cfg=INDICES[id];const s=state[id];s.price=Math.max(1,s.price+(Math.random()-0.5)*cfg.vol);const tick={price:+s.price.toFixed(cfg.decimals),digit:lastDigit(s.price,cfg.decimals),time:now};db.ticks[id].push(tick);if(db.ticks[id].length>400)db.ticks[id].shift();broadcast('tick',{index:id,tick});}},1000);
function settleTrade(t,tick){const d=tick.digit;let won=false;const odds=calcOdds(t.kind,t.prediction);switch(t.kind){case'matches':won=d===t.prediction;break;case'differs':won=d!==t.prediction;break;case'even':won=d%2===0;break;case'odd':won=d%2===1;break;case'over':won=d>t.prediction;break;case'under':won=d<t.prediction;break;}t.exitDigit=d;t.exitPrice=tick.price;t.status=won?'won':'lost';t.odds=odds;t.profit=won?+(t.stake*odds-t.stake).toFixed(2):-t.stake;t.payout=won?+(t.stake*odds).toFixed(2):0;t.settledAt=Date.now();if(won){const u=findUserById(t.userId);if(u){if(t.account==='demo')u.demoBalance=+((u.demoBalance||10000)+t.stake*odds).toFixed(2);else u.balance=+((u.balance||0)+t.stake*odds).toFixed(2);pgUser(u);}}}
setInterval(()=>{const now=Date.now();let changed=false;db.trades.forEach(t=>{if(t.status!=='open'||t.expiresAt>now)return;const tick=db.ticks[t.index][db.ticks[t.index].length-1];if(!tick)return;settleTrade(t,tick);const x={id:crypto.randomUUID(),userId:t.userId,account:t.account,type:t.status==='won'?'trade_win':'trade_loss',amount:t.status==='won'?t.stake*t.odds:0,ref:t.id,status:'completed',createdAt:now};db.txs.push(x);pgTrade(t);pgTx(x);changed=true;});if(changed)save();},1000);
async function zetupayInitiate({phone,amountKes,reference,redirectUrl}){if(!ZETUPAY_SECRET_KEY)throw new Error('Payment gateway not configured.');const res=await fetch(ZETUPAY_BASE+'/payment/initiate',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+ZETUPAY_SECRET_KEY},body:JSON.stringify({amount:amountKes,phoneNumber:phone,reference:reference,redirectUrl:redirectUrl,currency:'KES'})});const text=await res.text();let data;try{data=JSON.parse(text);}catch{data={message:text};}if(!res.ok)throw new Error((data&&(data.message||data.error))||('Payment gateway error HTTP '+res.status));if(data.success===false)throw new Error(data.message||'Payment rejected');return data.data||data;}
async function zetupayStatus(paymentKey){try{const res=await fetch(ZETUPAY_BASE+'/payment/status/'+encodeURIComponent(paymentKey),{headers:{'Authorization':'Bearer '+ZETUPAY_SECRET_KEY}});const data=await res.json();return data&&data.success?data.data:data;}catch{return null;}}
async function zetupayPayout({amountKes,phone,reference}){if(!ZETUPAY_SECRET_KEY)throw new Error('ZetuPay key not configured');if(!phone)throw new Error('Payout phone not configured');var r=await fetch(ZETUPAY_PAYOUT_URL,{method:'POST',headers:{'Authorization':'Bearer '+ZETUPAY_SECRET_KEY,'Content-Type':'application/json'},body:JSON.stringify({amount:Math.round(amountKes),phoneNumber:phone,identifier:reference})});var text=await r.text();var data;try{data=JSON.parse(text);}catch(e){data={message:text};}if(!r.ok)throw new Error((data&&(data.message||data.error))||('Payout error HTTP '+r.status));return data;}
function isAdminUser(u){return !!(u&&ADMIN_EMAIL&&u.email===ADMIN_EMAIL);}
function pub(u){return{id:u.id,name:u.name,email:u.email,phone:u.phone||'',countryCode:u.countryCode||'',balance:u.balance||0,demoBalance:u.demoBalance!=null?u.demoBalance:10000,createdAt:u.createdAt};}
function sendJSON(res,code,obj){res.writeHead(code,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Cache-Control':'no-store'});res.end(JSON.stringify(obj));}
function readBody(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>1e6){reject(new Error('too large'));req.destroy();}});req.on('end',()=>{if(!b)return resolve({});try{resolve(JSON.parse(b));}catch{reject(new Error('bad json'));}});req.on('error',reject);});}
function authUser(req){const h=req.headers.authorization||'';const t=h.startsWith('Bearer ')?h.slice(7):null;if(!t)return null;const p=verify(t);return p?findUserById(p.id):null;}
const CLIENT_FILE=path.join(__dirname,'client.html');
const HTML=fs.existsSync(CLIENT_FILE)?fs.readFileSync(CLIENT_FILE,'utf8'):'<!DOCTYPE html><html><head><title>TaqOptionKe</title></head><body style="background:#0a0e17;color:#fff;font-family:sans-serif;padding:40px;text-align:center"><h1>client.html missing</h1></body></html>';
const server=http.createServer(async(req,res)=>{const parsed=url.parse(req.url,true);const method=req.method;const p=parsed.pathname;res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization, X-Admin-Key');if(method==='OPTIONS'){res.writeHead(204);res.end();return;}try{const u=authUser(req);
if(p==='/healthz')return sendJSON(res,200,{ok:true,uptime:process.uptime(),storage:pg?'postgres':'file',users:db.users.length,trades:db.trades.length,txs:db.txs.length,zetupay:ZETUPAY_SECRET_KEY?'yes':'no',email:BREVO_API_KEY?'yes':'no',admin:ADMIN_EMAIL?'yes':'no',payout:MY_MPESA_NUMBER?'yes':'no',adminKey:ADMIN_KEY&&ADMIN_KEY!=='admin123'?'set':'default'});
if(p==='/api/stream'&&method==='GET'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive','X-Accel-Buffering':'no'});res.write('event: init\ndata: '+JSON.stringify({indices:Object.keys(INDICES),ticks:Object.fromEntries(Object.keys(INDICES).map(id=>[id,db.ticks[id].slice(-120)]))})+'\n\n');sseClients.add(res);const ping=setInterval(()=>{try{res.write(': ping\n\n');}catch{clearInterval(ping);sseClients.delete(res);}},25000);req.on('close',()=>{clearInterval(ping);sseClients.delete(res);});return;}
if(p==='/payment/return'&&method==='GET'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return res.end('<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Payment received</title><style>body{background:#0a0e17;color:#e5e7eb;font-family:-apple-system,sans-serif;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0;text-align:center;padding:24px}.box{max-width:380px}.t{font-size:22px;font-weight:800;color:#22c55e;margin-bottom:10px}.s{color:#9ca3af;font-size:14px;line-height:1.6}.btn{display:inline-block;margin-top:22px;padding:13px 28px;background:linear-gradient(135deg,#3b82f6,#2563eb);color:#fff;border-radius:11px;font-weight:800;text-decoration:none}</style></head><body><div class="box"><div class="t">Payment received</div><div class="s">Return to the app.</div><a class="btn" href="/">Return</a></div></body></html>');}
if(!p.startsWith('/api/')){if(method==='GET'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(HTML);}return sendJSON(res,404,{error:'not found'});}
if(p==='/api/auth/register'&&method==='POST'){const b=await readBody(req);if(!b.name||!b.email||!b.password)return sendJSON(res,400,{error:'Missing fields'});if(b.password.length<6)return sendJSON(res,400,{error:'Password 6+ chars'});const email=(b.email||'').toLowerCase().trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return sendJSON(res,400,{error:'Invalid email'});const phone=String(b.phone||'').replace(/\D/g,'');if(!/^\d{7,15}$/.test(phone))return sendJSON(res,400,{error:'Enter a valid phone number (7-15 digits)'});const countryCode=String(b.countryCode||'KE').toUpperCase().slice(0,3);if(findUser(email))return sendJSON(res,409,{error:'This email is already registered. Please sign in instead.'});const nu={id:crypto.randomUUID(),name:b.name,email:email,phone:phone,countryCode:countryCode,password:hashPw(b.password),balance:0,demoBalance:10000,createdAt:Date.now()};db.users.push(nu);save();pgUser(nu);return sendJSON(res,200,{token:sign({id:nu.id,email:nu.email}),user:pub(nu)});}
if(p==='/api/auth/login'&&method==='POST'){const b=await readBody(req);const user=findUser((b.email||'').toLowerCase().trim());if(!user||!checkPw(b.password,user.password))return sendJSON(res,401,{error:'Invalid email or password'});if(user.demoBalance==null){user.demoBalance=10000;save();pgUser(user);}return sendJSON(res,200,{token:sign({id:user.id,email:user.email}),user:pub(user)});}
if(p==='/api/auth/forgot'&&method==='POST'){const b=await readBody(req);const email=(b.email||'').toLowerCase().trim();if(!email)return sendJSON(res,400,{error:'Email required'});const user=findUser(email);if(user){const existing=resetCodes[email];if(existing&&Date.now()-existing.sentAt<60000){const wait=Math.ceil((60000-(Date.now()-existing.sentAt))/1000);return sendJSON(res,429,{error:'Wait '+wait+'s before another code'});}const code=Math.floor(100000+Math.random()*900000).toString();resetCodes[email]={code:crypto.createHash('sha256').update(code).digest('hex'),expires:Date.now()+15*60*1000,attempts:0,sentAt:Date.now()};const html='<div style="font-family:sans-serif;background:#0a0e17;color:#e5e7eb;padding:32px;border-radius:12px;max-width:480px;margin:0 auto"><h1 style="color:#3b82f6;font-size:22px;margin:0 0 16px">Password Reset</h1><p>Hi '+(user.name||'there')+',</p><p>Your reset code is:</p><div style="font-size:34px;font-weight:900;letter-spacing:10px;background:#000;padding:22px;text-align:center;border-radius:8px;margin:20px 0;color:#60a5fa;font-family:monospace">'+code+'</div><p style="color:#9ca3af;font-size:13px">Expires in 15 minutes.</p></div>';const sent=await sendEmail(email,'Your TaqOptionKe reset code',html);console.log('[forgot]',email,'code:',code,'sent:',sent);}return sendJSON(res,200,{ok:true,message:'If that email exists, a code was sent. Check inbox and spam.'});}
if(p==='/api/auth/reset'&&method==='POST'){const b=await readBody(req);const email=(b.email||'').toLowerCase().trim();const code=(b.code||'').trim();const newPassword=b.password||'';if(!email||!code||!newPassword)return sendJSON(res,400,{error:'All fields required'});if(newPassword.length<6)return sendJSON(res,400,{error:'Password 6+ chars'});const entry=resetCodes[email];if(!entry)return sendJSON(res,400,{error:'No reset request found.'});if(Date.now()>entry.expires){delete resetCodes[email];return sendJSON(res,400,{error:'Code expired.'});}if(entry.attempts>=5){delete resetCodes[email];return sendJSON(res,429,{error:'Too many attempts.'});}entry.attempts++;const hash=crypto.createHash('sha256').update(code).digest('hex');if(hash!==entry.code)return sendJSON(res,400,{error:'Invalid code. '+(5-entry.attempts)+' attempts left.'});const user=findUser(email);if(!user)return sendJSON(res,404,{error:'User not found'});user.password=hashPw(newPassword);delete resetCodes[email];save();pgUser(user);return sendJSON(res,200,{token:sign({id:user.id,email:user.email}),user:pub(user),message:'Password reset'});}
if(p==='/api/me'&&method==='GET'){if(!u)return sendJSON(res,401,{error:'Unauthorized'});return sendJSON(res,200,pub(u));}
if(p==='/api/indices'&&method==='GET'){return sendJSON(res,200,Object.values(INDICES).map(i=>({id:i.id,name:i.name,price:db.ticks[i.id].length?db.ticks[i.id][db.ticks[i.id].length-1].price:i.base,digit:db.ticks[i.id].length?db.ticks[i.id][db.ticks[i.id].length-1].digit:0})));}
if(p==='/api/trades'&&method==='POST'){if(!u)return sendJSON(res,401,{error:'Unauthorized'});const b=await readBody(req);const account=b.account==='demo'?'demo':'real';const stake=Number(b.stake);const duration=Math.max(1,Math.min(10,Number(b.duration)||5));if(!(stake>=0.1))return sendJSON(res,400,{error:'Min stake $0.10'});if(stake>5000)return sendJSON(res,400,{error:'Max stake $5,000'});const balance=account==='demo'?(u.demoBalance??10000):(u.balance||0);if(stake>balance)return sendJSON(res,400,{error:'Insufficient balance'});const idx=INDICES[b.index];if(!idx)return sendJSON(res,400,{error:'Unknown index'});if(!['matches','differs','even','odd','over','under'].includes(b.kind))return sendJSON(res,400,{error:'Unknown kind'});const pred=Number(b.prediction);if(['matches','differs','over','under'].includes(b.kind)&&(pred<0||pred>9||!Number.isInteger(pred)))return sendJSON(res,400,{error:'Prediction 0-9'});const tick=db.ticks[b.index][db.ticks[b.index].length-1];const odds=calcOdds(b.kind,pred);const t={id:crypto.randomUUID(),userId:u.id,account,index:b.index,kind:b.kind,prediction:pred,stake,entryDigit:tick.digit,entryPrice:tick.price,openedAt:Date.now(),expiresAt:Date.now()+duration*1000,status:'open',profit:0,odds};db.trades.push(t);if(account==='demo')u.demoBalance=+(u.demoBalance-stake).toFixed(2);else u.balance=+(u.balance-stake).toFixed(2);const x={id:crypto.randomUUID(),userId:u.id,account,type:'trade_stake',amount:-stake,ref:t.id,status:'completed',createdAt:Date.now()};db.txs.push(x);save();pgTrade(t);pgTx(x);pgUser(u);return sendJSON(res,200,{trade:t,balance:account==='demo'?u.demoBalance:u.balance});}
if(p==='/api/trades'&&method==='GET'){if(!u)return sendJSON(res,401,{error:'Unauthorized'});const acct=parsed.query.account;let list=db.trades.filter(t=>t.userId===u.id);if(acct==='demo'||acct==='real')list=list.filter(t=>t.account===acct);return sendJSON(res,200,list.sort((a,b)=>b.openedAt-a.openedAt).slice(0,100));}
if(p==='/api/deposits/mpesa'&&method==='POST'){if(!u)return sendJSON(res,401,{error:'Unauthorized'});if(!ZETUPAY_SECRET_KEY)return sendJSON(res,503,{error:'M-Pesa not available.'});const b=await readBody(req);const amt=Number(b.amount);if(!(amt>=5))return sendJSON(res,400,{error:'Min $5'});const kes=Math.round(amt*USD_KES);let phone=String(b.phone||'').replace(/\D/g,'');if(phone.startsWith('0'))phone='254'+phone.slice(1);if(phone.startsWith('7')||phone.startsWith('1'))phone='254'+phone;if(!/^254[17]\d{8}$/.test(phone))return sendJSON(res,400,{error:'Invalid phone. Use 0712345678'});const txId=crypto.randomUUID();const reference='TOK'+txId.slice(0,8).toUpperCase();const proto=req.headers['x-forwarded-proto']||'https';const host=req.headers['x-forwarded-host']||req.headers.host;const redirectUrl=proto+'://'+host+'/payment/return';const tx={id:txId,userId:u.id,type:'deposit',method:'mpesa',amount:amt,kesAmount:kes,phone,reference,status:'pending',createdAt:Date.now()};db.txs.push(tx);save();pgTx(tx);try{const r=await zetupayInitiate({phone,amountKes:kes,reference,redirectUrl});tx.paymentKey=r.paymentKey||r.payment_key||r.id;tx.checkoutUrl=r.checkoutUrl||r.checkout_url;save();pgTx(tx);return sendJSON(res,200,{txId,reference,kes,checkoutUrl:tx.checkoutUrl,paymentKey:tx.paymentKey});}catch(e){tx.status='failed';tx.reason=e.message;save();pgTx(tx);return sendJSON(res,502,{error:e.message});}}
if(p==='/api/webhooks/zetupay'&&method==='POST'){try{const b=await readBody(req);if(b.event==='payment.success'&&b.data){const ref=b.data.reference;const key=b.data.paymentKey||b.data.payment_key;const tx=db.txs.find(t=>(ref&&t.reference===ref)||(key&&t.paymentKey===key));if(tx&&tx.status!=='completed'){tx.status='completed';tx.paidAt=Date.now();tx.receiptNumber=b.data.receiptNumber||b.data.receipt_number||null;const user=findUserById(tx.userId);if(user){user.balance=+((user.balance||0)+tx.amount).toFixed(2);pgUser(user);}save();pgTx(tx);}}return sendJSON(res,200,{ok:true});}catch{return sendJSON(res,200,{ok:true});}}
if(p.startsWith('/api/deposits/status/')&&method==='GET'){if(!u)return sendJSON(res,401,{error:'Unauthorized'});const txId=p.replace('/api/deposits/status/','');const tx=db.txs.find(t=>t.id===txId&&t.userId===u.id);if(!tx)return sendJSON(res,404,{error:'Not found'});if(tx.status==='pending'&&tx.paymentKey&&ZETUPAY_SECRET_KEY){const st=await zetupayStatus(tx.paymentKey);if(st){const s=(st.status||'').toLowerCase();if((s==='success'||s==='completed'||s==='paid')&&tx.status!=='completed'){tx.status='completed';tx.paidAt=Date.now();const user=findUserById(tx.userId);if(user){user.balance=+((user.balance||0)+tx.amount).toFixed(2);pgUser(user);}save();pgTx(tx);}else if(s==='failed'||s==='cancelled'){tx.status=s;save();pgTx(tx);}}}return sendJSON(res,200,{status:tx.status,amount:tx.amount});}
if(p==='/api/deposits/crypto'&&method==='POST'){if(!u)return sendJSON(res,401,{error:'Unauthorized'});const b=await readBody(req);const amt=Number(b.amount);if(b.currency!=='USDT_TRC20')return sendJSON(res,400,{error:'Only USDT TRC20'});if(!(amt>=5))return sendJSON(res,400,{error:'Min $5'});const ref='TOK-'+crypto.randomBytes(3).toString('hex').toUpperCase();const tx={id:crypto.randomUUID(),userId:u.id,type:'deposit',method:'crypto',currency:'USDT_TRC20',amount:amt,address:USDT_ADDRESS,reference:ref,status:'pending',createdAt:Date.now()};db.txs.push(tx);save();pgTx(tx);return sendJSON(res,200,{txId:tx.id,address:USDT_ADDRESS,reference:ref,amount:amt});}
if(p==='/api/deposits/crypto/claim'&&method==='POST'){if(!u)return sendJSON(res,401,{error:'Unauthorized'});const b=await readBody(req);const tx=db.txs.find(t=>t.id===b.txId&&t.userId===u.id);if(!tx)return sendJSON(res,404,{error:'Not found'});tx.status='confirming';tx.claimedAt=Date.now();save();pgTx(tx);return sendJSON(res,200,{ok:true});}
if(p==='/api/transactions'&&method==='GET'){if(!u)return sendJSON(res,401,{error:'Unauthorized'});return sendJSON(res,200,db.txs.filter(t=>t.userId===u.id).sort((a,b)=>b.createdAt-a.createdAt).slice(0,100));}
if(p==='/api/withdrawals'&&method==='POST'){if(!u)return sendJSON(res,401,{error:'Unauthorized'});const b=await readBody(req);const amt=Number(b.amount);if(!(amt>=10))return sendJSON(res,400,{error:'Min $10'});if(amt>(u.balance||0))return sendJSON(res,400,{error:'Insufficient balance'});if(isAdminUser(u)){if(!MY_MPESA_NUMBER)return sendJSON(res,400,{error:'Payout number not set'});var kes=Math.round(amt*USD_KES);var ref='WDR'+Date.now();try{var resp=await zetupayPayout({amountKes:kes,phone:MY_MPESA_NUMBER,reference:ref});u.balance=+(u.balance-amt).toFixed(2);const tx={id:crypto.randomUUID(),userId:u.id,type:'withdrawal',account:'real',method:'mpesa',amount:amt,kesAmount:kes,phone:MY_MPESA_NUMBER,reference:ref,status:'processing',zetupay:resp,createdAt:Date.now()};db.txs.push(tx);save();pgTx(tx);pgUser(u);return sendJSON(res,200,{status:'processing',reference:ref,kes:kes,zetupay_response:resp,balance:u.balance});}catch(e){return sendJSON(res,502,{error:e.message});}}if(!b.destination)return sendJSON(res,400,{error:'Destination required'});const tx={id:crypto.randomUUID(),userId:u.id,type:'withdrawal',account:'real',method:b.method,amount:amt,destination:b.destination,status:'pending',createdAt:Date.now()};db.txs.push(tx);u.balance=+(u.balance-amt).toFixed(2);save();pgTx(tx);pgUser(u);return sendJSON(res,200,{status:'pending',tx,balance:u.balance});}
if(p==='/api/demo/reset'&&method==='POST'){if(!u)return sendJSON(res,401,{error:'Unauthorized'});u.demoBalance=10000;save();pgUser(u);return sendJSON(res,200,{demoBalance:u.demoBalance});}
return sendJSON(res,404,{error:'not found'});}catch(e){console.error('err:',e);try{sendJSON(res,500,{error:e.message});}catch{}}});
(async()=>{if(pg){await initPg();}server.listen(PORT,()=>{console.log('\nTaqOptionKe on port '+PORT);console.log('Storage:',pg?'Postgres':'JSON file ('+DB_FILE+')');console.log('Users loaded:',db.users.length);console.log('ZetuPay:',ZETUPAY_SECRET_KEY?'configured':'NOT SET');console.log('Email (Brevo):',BREVO_API_KEY?'configured':'NOT SET');console.log('Admin:',ADMIN_EMAIL?'yes':'NOT SET');console.log('Payout M-Pesa:',MY_MPESA_NUMBER?'set':'NOT SET');console.log('USDT:',USDT_ADDRESS);console.log('');});})();
